### PR TITLE
Fix load path for elpa packages.

### PR DESCRIPTION
**Pull request by infinitisno**
Hello.

See: https://github.com/vlaci/nix-doom-emacs/issues/300

### CODE REVIEW

**Comment by berbiche** [comment]
I confirm this fixes the emacs-overlay pgtkgcc package

**Comment by ulysses4ever** [comment]
Very cool! @vlaci could you please merge?

**Comment by vlaci** [comment]
Thanks!

**Comment by ulysses4ever** [comment]
Is there anything that has to be done on the vlaci/nix-doom-emacs's end? 'Cause it's master seem to have the same problem with *Gcc as before.

**Comment by vlaci** [comment]
I've updated the reference in `develop` branch of nix-doom-emacs

**Comment by ulysses4ever** [comment]
Cool, thank you!

**Pull request merged**
